fn i32_ops(a: int32, b: int32) -> tuple[int32, int32, int32, int32, int32, int32] {
    (a + b, a - b, a * b, a / b, a % b, -a)
}

fn u32_ops(a: uint32, b: uint32) -> tuple[uint32, uint32, uint32, uint32, uint32, uint32] {
    (a + b, a - b, a * b, a / b, a % b, -a)
}

fn i64_ops(a: i64, b: i64) -> tuple[i64, i64, i64, i64, i64, i64] {
    (a + b, a - b, a * b, a / b, a % b, -a)
}

fn u64_ops(a: u64, b: u64) -> tuple[u64, u64, u64, u64, u64, u64] {
    (a + b, a - b, a * b, a / b, a % b, -a)
}

fn f32_ops(a: float32, b: float32) -> tuple[float32, float32, float32, float32, float32, float32] {
    (a + b, a - b, a * b, a / b, a % b, -a)
}

fn f64_ops(a: f64, b: f64) -> tuple[f64, f64, f64, f64, f64, f64] {
    (a + b, a - b, a * b, a / b, a % b, -a)
}

fn main() -> void {}
