//! Hand-maintained executable mirror of the v10 opcode table (Stilla
//! LLIR Instruction Set.md §4–§9): the logical `Opcode = enum(u16)`
//! with explicit logical values, the `OpInfo` schema rows, and comptime
//! metadata, consumed by `llir.zig`. The codec/bijection tests in
//! `llir.zig` are the executable proof of the table (counts, uniqueness,
//! alignment, round-trip).
//!
//! v10: the integer arithmetic families are **typed** — every member
//! carries its full rep (`add.i32`, `add.u32`, `add.i64`, `add.u64`,
//! then `f32`/`f64` where the family has float members), computes at
//! that width, and self-canonicalizes its result cell (§4). The
//! widthless arithmetic opcodes and the `sext32`/`zext32` canonicalization
//! pair are gone. The immediate families are the four-rep spellings
//! (`addi.i32`…`maddi.u64`); the bitwise ops (`and`/`or`/`xor` and their
//! immediate forms) stay widthless — they are rep-agnostic on canonical
//! cells. The E-type `neg` family fills the codes `1–3` its retired
//! widthless predecessors vacated, and codes `6–7` (the former
//! `sext32`/`zext32` slots) are reserved. Logical values run 1–273 in
//! table order with no holes, and every format's encoded selectors are
//! contiguous except the reserved holes (R 0–115, B 0–19, C 0–63, E
//! 0–43 with `6–7` and `13/15/17/19` reserved, I 0–30 with selector 10
//! reserved — the former `result_take` slot, kept so the `slot_*`
//! encodings never move; U keeps `jal`/`j` sharing prefix 0, `auipc` 1,
//! `lui` 2).

pub const Format = enum(u8) {
    /// R-type: `00 | code(9) | a(7) | b(7) | c(7)`.
    r,
    /// B-type: `01 | code(6) | lhs(7) | rhs_or_imm7(7) | offs10`.
    b,
    /// I-type: `110 | code(6) | a(7) | imm16`.
    i,
    /// C-type: `111000 | code(6) | reserved(6)=0 | a(7) | b(7)`.
    c,
    /// E-type: `111001 | code(6) | reserved(6)=0 | a(7) | b(7)`.
    e,
    /// U-type: `op(5) | a(7) | imm20`. Four opcodes over three prefixes:
    /// `11101` holds both `jal` (register field `ra`) and `j` (register
    /// field fixed `0`, Instruction Set §9.1).
    u,
};

/// The numeric representation of a typed family member, fixed by the
/// opcode's rep suffix (integer-4 `i32, u32, i64, u64` then float-2
/// `f32, f64`). `repOf(op)` reads it from `opInfo`; the alignment of
/// every family's logical values is machine-proven (llir.zig tests).
pub const Rep = enum(u8) { i32, u32, i64, u64, f32, f64 };

/// One operand field's schema: its role plus the special-register
/// permission (Stilla LLIR Instruction Set.md §3.2). Register fields
/// name F/T/`zero`/`ra`/`cond` per the value; immediate fields fix
/// the interpretation of the field's bits.
pub const Field = enum(u8) {
    cond,
    dst,
    dst_movw,
    dst_real,
    dst_u,
    id,
    imm,
    imm16,
    imm20,
    link,
    mask,
    none,
    offs10,
    offs16,
    src,
    src_f,
    src_real,
    src_t,
    tested,
};

/// One schema row: the format + encoded selector, the rep (null for
/// untyped opcodes), the per-field operand schema, and the trap/
/// terminator attributes (Instruction Set §4–§9).
pub const OpInfo = struct {
    name: []const u8,
    format: Format,
    /// The per-format encoded selector: 9 bits (R), 6 (B/I/C/E), or
    /// the 5-bit U prefix index 0–2 (jal/auipc/lui).
    code: u16,
    rep: ?Rep,
    a: Field,
    b: Field,
    c: Field,
    may_trap: bool,
    terminator: bool,
};
/// The complete logical opcode set — 273 opcodes with explicit logical
/// values, contiguous 1–273 in table order (each format's encoded
/// selectors are likewise contiguous runs, so a family's members are
/// consecutive — no alignment holes, no inherited slots). Names are
/// the canonical spellings with dots replaced by underscores;
/// `OpInfo.name` keeps the dotted spelling.
pub const Opcode = enum(u16) {

    // --- R-type (00 | code(9) | a(7) | b(7) | c(7)) ---
    add_i32 = 1,
    add_u32 = 2,
    add_i64 = 3,
    add_u64 = 4,
    add_f32 = 5,
    add_f64 = 6,
    sub_i32 = 7,
    sub_u32 = 8,
    sub_i64 = 9,
    sub_u64 = 10,
    sub_f32 = 11,
    sub_f64 = 12,
    mul_i32 = 13,
    mul_u32 = 14,
    mul_i64 = 15,
    mul_u64 = 16,
    mul_f32 = 17,
    mul_f64 = 18,
    div_i32 = 19,
    div_u32 = 20,
    div_i64 = 21,
    div_u64 = 22,
    div_f32 = 23,
    div_f64 = 24,
    rem_i32 = 25,
    rem_u32 = 26,
    rem_i64 = 27,
    rem_u64 = 28,
    rem_f32 = 29,
    rem_f64 = 30,
    min_i32 = 31,
    min_u32 = 32,
    min_i64 = 33,
    min_u64 = 34,
    min_f32 = 35,
    min_f64 = 36,
    max_i32 = 37,
    max_u32 = 38,
    max_i64 = 39,
    max_u64 = 40,
    max_f32 = 41,
    max_f64 = 42,
    addi_i32 = 43,
    addi_u32 = 44,
    addi_i64 = 45,
    addi_u64 = 46,
    subi_i32 = 47,
    subi_u32 = 48,
    subi_i64 = 49,
    subi_u64 = 50,
    muli_i32 = 51,
    muli_u32 = 52,
    muli_i64 = 53,
    muli_u64 = 54,
    divi_i32 = 55,
    divi_u32 = 56,
    divi_i64 = 57,
    divi_u64 = 58,
    remi_i32 = 59,
    remi_u32 = 60,
    remi_i64 = 61,
    remi_u64 = 62,
    shl_i32 = 63,
    shl_u32 = 64,
    shl_i64 = 65,
    shl_u64 = 66,
    shr_i32 = 67,
    shr_u32 = 68,
    shr_i64 = 69,
    shr_u64 = 70,
    shli_i32 = 71,
    shli_u32 = 72,
    shli_i64 = 73,
    shli_u64 = 74,
    shri_i32 = 75,
    shri_u32 = 76,
    shri_i64 = 77,
    shri_u64 = 78,
    and_ = 79,
    or_ = 80,
    xor = 81,
    andi = 82,
    ori = 83,
    xori = 84,
    madd_i32 = 85,
    madd_u32 = 86,
    madd_i64 = 87,
    madd_u64 = 88,
    madd_f32 = 89,
    madd_f64 = 90,
    msub_i32 = 91,
    msub_u32 = 92,
    msub_i64 = 93,
    msub_u64 = 94,
    msub_f32 = 95,
    msub_f64 = 96,
    maddi_i32 = 97,
    maddi_u32 = 98,
    maddi_i64 = 99,
    maddi_u64 = 100,
    load_member = 101,
    read_field = 102,
    read_tuple = 103,
    read_payload = 104,
    read_index = 105,
    read_indexi = 106,
    concat = 107,
    tail = 108,
    unpack_variant = 109,
    borrow_variant = 110,
    type_is = 111,
    any_pack_copy = 112,
    any_pack_move = 113,
    any_unpack_copy = 114,
    any_unpack_move = 115,
    cmov = 116,

    // --- B-type (01 | code(6) | lhs(7) | rhs_or_imm7(7) | offs10) ---
    beq = 117,
    beq_f32 = 118,
    beq_f64 = 119,
    bne = 120,
    bne_f32 = 121,
    bne_f64 = 122,
    blt = 123,
    bltu = 124,
    blt_f32 = 125,
    blt_f64 = 126,
    ble = 127,
    bleu = 128,
    ble_f32 = 129,
    ble_f64 = 130,
    blti = 131,
    bltiu = 132,
    beqi = 133,
    bnei = 134,
    tbz = 135,
    tbnz = 136,

    // --- C-type (111000 | code(6) | reserved(6)=0 | a(7) | b(7)) ---
    seq = 137,
    seq_f32 = 138,
    seq_f64 = 139,
    sne = 140,
    sne_f32 = 141,
    sne_f64 = 142,
    slt = 143,
    sltu = 144,
    slt_f32 = 145,
    slt_f64 = 146,
    sle_f32 = 147,
    sle_f64 = 148,
    bool_eq = 149,
    bool_ne = 150,
    str_eq = 151,
    str_ne = 152,
    slti = 153,
    sltiu = 154,
    sgti = 155,
    sgtiu = 156,
    seqi = 157,
    snei = 158,
    cvt_b_i32 = 159,
    cvt_b_u32 = 160,
    cvt_b_f32 = 161,
    cvt_b_f64 = 162,
    cvt_i32_b = 163,
    cvt_i32_u32 = 164,
    cvt_i32_f32 = 165,
    cvt_i32_f64 = 166,
    cvt_u32_b = 167,
    cvt_u32_i32 = 168,
    cvt_u32_f32 = 169,
    cvt_u32_f64 = 170,
    cvt_f32_b = 171,
    cvt_f32_i32 = 172,
    cvt_f32_u32 = 173,
    cvt_f32_f64 = 174,
    cvt_f64_b = 175,
    cvt_f64_i32 = 176,
    cvt_f64_u32 = 177,
    cvt_f64_f32 = 178,
    // The 64-bit integer cast matrix (codes 42–63): `i64`/`u64` sources
    // and targets complete the `7 × 7` cast matrix over
    // `b, i32, u32, i64, u64, f32, f64` minus the identity entries.
    cvt_b_i64 = 179,
    cvt_b_u64 = 180,
    cvt_i32_i64 = 181,
    cvt_i32_u64 = 182,
    cvt_u32_i64 = 183,
    cvt_u32_u64 = 184,
    cvt_i64_b = 185,
    cvt_i64_i32 = 186,
    cvt_i64_u32 = 187,
    cvt_i64_u64 = 188,
    cvt_i64_f32 = 189,
    cvt_i64_f64 = 190,
    cvt_u64_b = 191,
    cvt_u64_i32 = 192,
    cvt_u64_u32 = 193,
    cvt_u64_i64 = 194,
    cvt_u64_f32 = 195,
    cvt_u64_f64 = 196,
    cvt_f32_i64 = 197,
    cvt_f32_u64 = 198,
    cvt_f64_i64 = 199,
    cvt_f64_u64 = 200,

    // --- E-type (111001 | code(6) | reserved(6)=0 | a(7) | b(7)) ---
    // `neg` is the typed integer-4 family: it fills codes 0–3 that its
    // retired widthless predecessors vacated; codes 6–7 (the former
    // `sext32`/`zext32` slots) are reserved.
    neg_i32 = 201,
    neg_u32 = 202,
    neg_i64 = 203,
    neg_u64 = 204,
    neg_f32 = 205,
    neg_f64 = 206,
    abs_i32 = 207,
    abs_i64 = 208,
    abs_f32 = 209,
    abs_f64 = 210,
    // clz/popcount are sign-agnostic, so the unsigned types alias the
    // signed member of the same width; the retired `clz_u32`/`clz_u64`/
    // `popcount_u32`/`popcount_u64` slots (13/15/17/19) stay unused.
    clz_i32 = 211,
    clz_i64 = 212,
    popcount_i32 = 213,
    popcount_i64 = 214,
    sqrt_f32 = 215,
    sqrt_f64 = 216,
    floor_f32 = 217,
    floor_f64 = 218,
    ceil_f32 = 219,
    ceil_f64 = 220,
    trunc_f32 = 221,
    trunc_f64 = 222,
    round_f32 = 223,
    round_f64 = 224,
    not = 225,
    read_tag = 226,
    copy = 227,
    borrow = 228,
    move = 229,
    release = 230,
    copy_retain = 231,
    replace_copy = 232,
    replace_move = 233,
    release_ret = 234,
    ret = 235,
    tailcall_self = 236,
    trap = 237,

    /// The generic take — a plain register transfer (`a = take(b)`)
    /// that clears its source, never a call-specific opcode. It closes
    /// the E-type run (E-code 43, after `trap`): the v10 successor of
    /// `result_take`, whose I-type selector 10 stays reserved so the
    /// `slot_*` encodings never move (Instruction Set §4).
    take = 238,

    // --- I-type (110 | code(6) | a(7) | imm16) ---
    const_ = 239,
    fn_ref = 240,
    module_ref = 241,
    syscall = 242,
    construct = 243,
    store_member = 244,
    unpack_struct = 245,
    unpack_tuple = 246,
    split_list = 247,
    switch_ = 248,
    jalr = 249,
    spill_take = 250,
    spill_put = 251,
    slot_retain = 252,
    slot_move = 253,
    slot_borrow = 254,
    slot_copy = 255,
    jr = 256,
    drop = 257,
    movwn0 = 258,
    movwn1 = 259,
    movwn2 = 260,
    movwn3 = 261,
    movwz0 = 262,
    movwz1 = 263,
    movwz2 = 264,
    movwz3 = 265,
    movwk0 = 266,
    movwk1 = 267,
    movwk2 = 268,
    movwk3 = 269,

    // --- U-type (op(5) | a(7) | imm20); 11101 splits jal/j by reg ---
    jal = 270,

    /// The unconditional intra-function jump: no link, no frame — it
    /// encodes as `jal`'s U-type word carrying the `zero` encoding as
    /// its no-link mark, and decodes back by that field (§9.1).
    j = 271,
    auipc = 272,
    lui = 273,
};

/// The schema row of every logical opcode. Exhaustive over `Opcode`:
/// adding an opcode without a row is a compile error, and the values
/// match the machine-proof table (llir.zig tests).
pub fn opInfo(op: Opcode) OpInfo {
    return switch (op) {
        .add_i32 => .{ .name = "add.i32", .format = .r, .code = 0, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .add_u32 => .{ .name = "add.u32", .format = .r, .code = 1, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .add_i64 => .{ .name = "add.i64", .format = .r, .code = 2, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .add_u64 => .{ .name = "add.u64", .format = .r, .code = 3, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .add_f32 => .{ .name = "add.f32", .format = .r, .code = 4, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .add_f64 => .{ .name = "add.f64", .format = .r, .code = 5, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .sub_i32 => .{ .name = "sub.i32", .format = .r, .code = 6, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .sub_u32 => .{ .name = "sub.u32", .format = .r, .code = 7, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .sub_i64 => .{ .name = "sub.i64", .format = .r, .code = 8, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .sub_u64 => .{ .name = "sub.u64", .format = .r, .code = 9, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .sub_f32 => .{ .name = "sub.f32", .format = .r, .code = 10, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .sub_f64 => .{ .name = "sub.f64", .format = .r, .code = 11, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .mul_i32 => .{ .name = "mul.i32", .format = .r, .code = 12, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .mul_u32 => .{ .name = "mul.u32", .format = .r, .code = 13, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .mul_i64 => .{ .name = "mul.i64", .format = .r, .code = 14, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .mul_u64 => .{ .name = "mul.u64", .format = .r, .code = 15, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .mul_f32 => .{ .name = "mul.f32", .format = .r, .code = 16, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .mul_f64 => .{ .name = "mul.f64", .format = .r, .code = 17, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .div_i32 => .{ .name = "div.i32", .format = .r, .code = 18, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .div_u32 => .{ .name = "div.u32", .format = .r, .code = 19, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .div_i64 => .{ .name = "div.i64", .format = .r, .code = 20, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .div_u64 => .{ .name = "div.u64", .format = .r, .code = 21, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .div_f32 => .{ .name = "div.f32", .format = .r, .code = 22, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .div_f64 => .{ .name = "div.f64", .format = .r, .code = 23, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .rem_i32 => .{ .name = "rem.i32", .format = .r, .code = 24, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .rem_u32 => .{ .name = "rem.u32", .format = .r, .code = 25, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .rem_i64 => .{ .name = "rem.i64", .format = .r, .code = 26, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .rem_u64 => .{ .name = "rem.u64", .format = .r, .code = 27, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = true, .terminator = false },
        .rem_f32 => .{ .name = "rem.f32", .format = .r, .code = 28, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .rem_f64 => .{ .name = "rem.f64", .format = .r, .code = 29, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .min_i32 => .{ .name = "min.i32", .format = .r, .code = 30, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .min_u32 => .{ .name = "min.u32", .format = .r, .code = 31, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .min_i64 => .{ .name = "min.i64", .format = .r, .code = 32, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .min_u64 => .{ .name = "min.u64", .format = .r, .code = 33, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .min_f32 => .{ .name = "min.f32", .format = .r, .code = 34, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .min_f64 => .{ .name = "min.f64", .format = .r, .code = 35, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .max_i32 => .{ .name = "max.i32", .format = .r, .code = 36, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .max_u32 => .{ .name = "max.u32", .format = .r, .code = 37, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .max_i64 => .{ .name = "max.i64", .format = .r, .code = 38, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .max_u64 => .{ .name = "max.u64", .format = .r, .code = 39, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .max_f32 => .{ .name = "max.f32", .format = .r, .code = 40, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .max_f64 => .{ .name = "max.f64", .format = .r, .code = 41, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .addi_i32 => .{ .name = "addi.i32", .format = .r, .code = 42, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .addi_u32 => .{ .name = "addi.u32", .format = .r, .code = 43, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .addi_i64 => .{ .name = "addi.i64", .format = .r, .code = 44, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .addi_u64 => .{ .name = "addi.u64", .format = .r, .code = 45, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .subi_i32 => .{ .name = "subi.i32", .format = .r, .code = 46, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .subi_u32 => .{ .name = "subi.u32", .format = .r, .code = 47, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .subi_i64 => .{ .name = "subi.i64", .format = .r, .code = 48, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .subi_u64 => .{ .name = "subi.u64", .format = .r, .code = 49, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .muli_i32 => .{ .name = "muli.i32", .format = .r, .code = 50, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .muli_u32 => .{ .name = "muli.u32", .format = .r, .code = 51, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .muli_i64 => .{ .name = "muli.i64", .format = .r, .code = 52, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .muli_u64 => .{ .name = "muli.u64", .format = .r, .code = 53, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .divi_i32 => .{ .name = "divi.i32", .format = .r, .code = 54, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .divi_u32 => .{ .name = "divi.u32", .format = .r, .code = 55, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .divi_i64 => .{ .name = "divi.i64", .format = .r, .code = 56, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .divi_u64 => .{ .name = "divi.u64", .format = .r, .code = 57, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .remi_i32 => .{ .name = "remi.i32", .format = .r, .code = 58, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .remi_u32 => .{ .name = "remi.u32", .format = .r, .code = 59, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .remi_i64 => .{ .name = "remi.i64", .format = .r, .code = 60, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .remi_u64 => .{ .name = "remi.u64", .format = .r, .code = 61, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = true, .terminator = false },
        .shl_i32 => .{ .name = "shl.i32", .format = .r, .code = 62, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shl_u32 => .{ .name = "shl.u32", .format = .r, .code = 63, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shl_i64 => .{ .name = "shl.i64", .format = .r, .code = 64, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shl_u64 => .{ .name = "shl.u64", .format = .r, .code = 65, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shr_i32 => .{ .name = "shr.i32", .format = .r, .code = 66, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shr_u32 => .{ .name = "shr.u32", .format = .r, .code = 67, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shr_i64 => .{ .name = "shr.i64", .format = .r, .code = 68, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shr_u64 => .{ .name = "shr.u64", .format = .r, .code = 69, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .shli_i32 => .{ .name = "shli.i32", .format = .r, .code = 70, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shli_u32 => .{ .name = "shli.u32", .format = .r, .code = 71, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shli_i64 => .{ .name = "shli.i64", .format = .r, .code = 72, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shli_u64 => .{ .name = "shli.u64", .format = .r, .code = 73, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shri_i32 => .{ .name = "shri.i32", .format = .r, .code = 74, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shri_u32 => .{ .name = "shri.u32", .format = .r, .code = 75, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shri_i64 => .{ .name = "shri.i64", .format = .r, .code = 76, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .shri_u64 => .{ .name = "shri.u64", .format = .r, .code = 77, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .and_ => .{ .name = "and", .format = .r, .code = 78, .rep = null, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .or_ => .{ .name = "or", .format = .r, .code = 79, .rep = null, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .xor => .{ .name = "xor", .format = .r, .code = 80, .rep = null, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .andi => .{ .name = "andi", .format = .r, .code = 81, .rep = null, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .ori => .{ .name = "ori", .format = .r, .code = 82, .rep = null, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .xori => .{ .name = "xori", .format = .r, .code = 83, .rep = null, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .madd_i32 => .{ .name = "madd.i32", .format = .r, .code = 84, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .madd_u32 => .{ .name = "madd.u32", .format = .r, .code = 85, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .madd_i64 => .{ .name = "madd.i64", .format = .r, .code = 86, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .madd_u64 => .{ .name = "madd.u64", .format = .r, .code = 87, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .madd_f32 => .{ .name = "madd.f32", .format = .r, .code = 88, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .madd_f64 => .{ .name = "madd.f64", .format = .r, .code = 89, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .msub_i32 => .{ .name = "msub.i32", .format = .r, .code = 90, .rep = .i32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .msub_u32 => .{ .name = "msub.u32", .format = .r, .code = 91, .rep = .u32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .msub_i64 => .{ .name = "msub.i64", .format = .r, .code = 92, .rep = .i64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .msub_u64 => .{ .name = "msub.u64", .format = .r, .code = 93, .rep = .u64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .msub_f32 => .{ .name = "msub.f32", .format = .r, .code = 94, .rep = .f32, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .msub_f64 => .{ .name = "msub.f64", .format = .r, .code = 95, .rep = .f64, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .maddi_i32 => .{ .name = "maddi.i32", .format = .r, .code = 96, .rep = .i32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .maddi_u32 => .{ .name = "maddi.u32", .format = .r, .code = 97, .rep = .u32, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .maddi_i64 => .{ .name = "maddi.i64", .format = .r, .code = 98, .rep = .i64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .maddi_u64 => .{ .name = "maddi.u64", .format = .r, .code = 99, .rep = .u64, .a = .dst, .b = .src, .c = .imm, .may_trap = false, .terminator = false },
        .load_member => .{ .name = "load_member", .format = .r, .code = 100, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .read_field => .{ .name = "read_field", .format = .r, .code = 101, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .read_tuple => .{ .name = "read_tuple", .format = .r, .code = 102, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .read_payload => .{ .name = "read_payload", .format = .r, .code = 103, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .read_index => .{ .name = "read_index", .format = .r, .code = 104, .rep = null, .a = .dst, .b = .src_real, .c = .src, .may_trap = true, .terminator = false },
        .read_indexi => .{ .name = "read_indexi", .format = .r, .code = 105, .rep = null, .a = .dst, .b = .src_real, .c = .mask, .may_trap = true, .terminator = false },
        .concat => .{ .name = "concat", .format = .r, .code = 106, .rep = null, .a = .dst, .b = .src_real, .c = .src_real, .may_trap = false, .terminator = false },
        .tail => .{ .name = "tail", .format = .r, .code = 107, .rep = null, .a = .dst, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .unpack_variant => .{ .name = "unpack_variant", .format = .r, .code = 108, .rep = null, .a = .id, .b = .src_real, .c = .imm, .may_trap = false, .terminator = false },
        .borrow_variant => .{ .name = "borrow_variant", .format = .r, .code = 109, .rep = null, .a = .id, .b = .src_real, .c = .imm, .may_trap = false, .terminator = false },
        .type_is => .{ .name = "type_is", .format = .r, .code = 110, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .any_pack_copy => .{ .name = "any_pack_copy", .format = .r, .code = 111, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .any_pack_move => .{ .name = "any_pack_move", .format = .r, .code = 112, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = false, .terminator = false },
        .any_unpack_copy => .{ .name = "any_unpack_copy", .format = .r, .code = 113, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = true, .terminator = false },
        .any_unpack_move => .{ .name = "any_unpack_move", .format = .r, .code = 114, .rep = null, .a = .dst, .b = .src_real, .c = .id, .may_trap = true, .terminator = false },
        .cmov => .{ .name = "cmov", .format = .r, .code = 115, .rep = null, .a = .dst, .b = .src, .c = .src, .may_trap = false, .terminator = false },
        .beq => .{ .name = "beq", .format = .b, .code = 0, .rep = null, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .beq_f32 => .{ .name = "beq.f32", .format = .b, .code = 1, .rep = .f32, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .beq_f64 => .{ .name = "beq.f64", .format = .b, .code = 2, .rep = .f64, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .bne => .{ .name = "bne", .format = .b, .code = 3, .rep = null, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .bne_f32 => .{ .name = "bne.f32", .format = .b, .code = 4, .rep = .f32, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .bne_f64 => .{ .name = "bne.f64", .format = .b, .code = 5, .rep = .f64, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .blt => .{ .name = "blt", .format = .b, .code = 6, .rep = null, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .bltu => .{ .name = "bltu", .format = .b, .code = 7, .rep = null, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .blt_f32 => .{ .name = "blt.f32", .format = .b, .code = 8, .rep = .f32, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .blt_f64 => .{ .name = "blt.f64", .format = .b, .code = 9, .rep = .f64, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .ble => .{ .name = "ble", .format = .b, .code = 10, .rep = null, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .bleu => .{ .name = "bleu", .format = .b, .code = 11, .rep = null, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .ble_f32 => .{ .name = "ble.f32", .format = .b, .code = 12, .rep = .f32, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .ble_f64 => .{ .name = "ble.f64", .format = .b, .code = 13, .rep = .f64, .a = .src, .b = .src, .c = .offs10, .may_trap = false, .terminator = false },
        .blti => .{ .name = "blti", .format = .b, .code = 14, .rep = null, .a = .src, .b = .imm, .c = .offs10, .may_trap = false, .terminator = false },
        .bltiu => .{ .name = "bltiu", .format = .b, .code = 15, .rep = null, .a = .src, .b = .imm, .c = .offs10, .may_trap = false, .terminator = false },
        .beqi => .{ .name = "beqi", .format = .b, .code = 16, .rep = null, .a = .src, .b = .imm, .c = .offs10, .may_trap = false, .terminator = false },
        .bnei => .{ .name = "bnei", .format = .b, .code = 17, .rep = null, .a = .src, .b = .imm, .c = .offs10, .may_trap = false, .terminator = false },
        .tbz => .{ .name = "tbz", .format = .b, .code = 18, .rep = null, .a = .tested, .b = .mask, .c = .offs10, .may_trap = false, .terminator = false },
        .tbnz => .{ .name = "tbnz", .format = .b, .code = 19, .rep = null, .a = .tested, .b = .mask, .c = .offs10, .may_trap = false, .terminator = false },
        .seq => .{ .name = "seq", .format = .c, .code = 0, .rep = null, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .seq_f32 => .{ .name = "seq.f32", .format = .c, .code = 1, .rep = .f32, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .seq_f64 => .{ .name = "seq.f64", .format = .c, .code = 2, .rep = .f64, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sne => .{ .name = "sne", .format = .c, .code = 3, .rep = null, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sne_f32 => .{ .name = "sne.f32", .format = .c, .code = 4, .rep = .f32, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sne_f64 => .{ .name = "sne.f64", .format = .c, .code = 5, .rep = .f64, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .slt => .{ .name = "slt", .format = .c, .code = 6, .rep = null, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sltu => .{ .name = "sltu", .format = .c, .code = 7, .rep = null, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .slt_f32 => .{ .name = "slt.f32", .format = .c, .code = 8, .rep = .f32, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .slt_f64 => .{ .name = "slt.f64", .format = .c, .code = 9, .rep = .f64, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sle_f32 => .{ .name = "sle.f32", .format = .c, .code = 10, .rep = .f32, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sle_f64 => .{ .name = "sle.f64", .format = .c, .code = 11, .rep = .f64, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .bool_eq => .{ .name = "bool_eq", .format = .c, .code = 12, .rep = null, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .bool_ne => .{ .name = "bool_ne", .format = .c, .code = 13, .rep = null, .a = .src, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .str_eq => .{ .name = "str_eq", .format = .c, .code = 14, .rep = null, .a = .src_real, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .str_ne => .{ .name = "str_ne", .format = .c, .code = 15, .rep = null, .a = .src_real, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .slti => .{ .name = "slti", .format = .c, .code = 16, .rep = null, .a = .src, .b = .imm, .c = .none, .may_trap = false, .terminator = false },
        .sltiu => .{ .name = "sltiu", .format = .c, .code = 17, .rep = null, .a = .src, .b = .imm, .c = .none, .may_trap = false, .terminator = false },
        .sgti => .{ .name = "sgti", .format = .c, .code = 18, .rep = null, .a = .src, .b = .imm, .c = .none, .may_trap = false, .terminator = false },
        .sgtiu => .{ .name = "sgtiu", .format = .c, .code = 19, .rep = null, .a = .src, .b = .imm, .c = .none, .may_trap = false, .terminator = false },
        .seqi => .{ .name = "seqi", .format = .c, .code = 20, .rep = null, .a = .src, .b = .imm, .c = .none, .may_trap = false, .terminator = false },
        .snei => .{ .name = "snei", .format = .c, .code = 21, .rep = null, .a = .src, .b = .imm, .c = .none, .may_trap = false, .terminator = false },
        .cvt_b_i32 => .{ .name = "cvt.b.i32", .format = .c, .code = 22, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_b_u32 => .{ .name = "cvt.b.u32", .format = .c, .code = 23, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_b_f32 => .{ .name = "cvt.b.f32", .format = .c, .code = 24, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_b_f64 => .{ .name = "cvt.b.f64", .format = .c, .code = 25, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i32_b => .{ .name = "cvt.i32.b", .format = .c, .code = 26, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i32_u32 => .{ .name = "cvt.i32.u32", .format = .c, .code = 27, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i32_f32 => .{ .name = "cvt.i32.f32", .format = .c, .code = 28, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i32_f64 => .{ .name = "cvt.i32.f64", .format = .c, .code = 29, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u32_b => .{ .name = "cvt.u32.b", .format = .c, .code = 30, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u32_i32 => .{ .name = "cvt.u32.i32", .format = .c, .code = 31, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u32_f32 => .{ .name = "cvt.u32.f32", .format = .c, .code = 32, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u32_f64 => .{ .name = "cvt.u32.f64", .format = .c, .code = 33, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f32_b => .{ .name = "cvt.f32.b", .format = .c, .code = 34, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f32_i32 => .{ .name = "cvt.f32.i32", .format = .c, .code = 35, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f32_u32 => .{ .name = "cvt.f32.u32", .format = .c, .code = 36, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f32_f64 => .{ .name = "cvt.f32.f64", .format = .c, .code = 37, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f64_b => .{ .name = "cvt.f64.b", .format = .c, .code = 38, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f64_i32 => .{ .name = "cvt.f64.i32", .format = .c, .code = 39, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f64_u32 => .{ .name = "cvt.f64.u32", .format = .c, .code = 40, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f64_f32 => .{ .name = "cvt.f64.f32", .format = .c, .code = 41, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_b_i64 => .{ .name = "cvt.b.i64", .format = .c, .code = 42, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_b_u64 => .{ .name = "cvt.b.u64", .format = .c, .code = 43, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i32_i64 => .{ .name = "cvt.i32.i64", .format = .c, .code = 44, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i32_u64 => .{ .name = "cvt.i32.u64", .format = .c, .code = 45, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u32_i64 => .{ .name = "cvt.u32.i64", .format = .c, .code = 46, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u32_u64 => .{ .name = "cvt.u32.u64", .format = .c, .code = 47, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i64_b => .{ .name = "cvt.i64.b", .format = .c, .code = 48, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i64_i32 => .{ .name = "cvt.i64.i32", .format = .c, .code = 49, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i64_u32 => .{ .name = "cvt.i64.u32", .format = .c, .code = 50, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i64_u64 => .{ .name = "cvt.i64.u64", .format = .c, .code = 51, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i64_f32 => .{ .name = "cvt.i64.f32", .format = .c, .code = 52, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_i64_f64 => .{ .name = "cvt.i64.f64", .format = .c, .code = 53, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u64_b => .{ .name = "cvt.u64.b", .format = .c, .code = 54, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u64_i32 => .{ .name = "cvt.u64.i32", .format = .c, .code = 55, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u64_u32 => .{ .name = "cvt.u64.u32", .format = .c, .code = 56, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u64_i64 => .{ .name = "cvt.u64.i64", .format = .c, .code = 57, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u64_f32 => .{ .name = "cvt.u64.f32", .format = .c, .code = 58, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_u64_f64 => .{ .name = "cvt.u64.f64", .format = .c, .code = 59, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f32_i64 => .{ .name = "cvt.f32.i64", .format = .c, .code = 60, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f32_u64 => .{ .name = "cvt.f32.u64", .format = .c, .code = 61, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f64_i64 => .{ .name = "cvt.f64.i64", .format = .c, .code = 62, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .cvt_f64_u64 => .{ .name = "cvt.f64.u64", .format = .c, .code = 63, .rep = null, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .neg_i32 => .{ .name = "neg.i32", .format = .e, .code = 0, .rep = .i32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .neg_u32 => .{ .name = "neg.u32", .format = .e, .code = 1, .rep = .u32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .neg_i64 => .{ .name = "neg.i64", .format = .e, .code = 2, .rep = .i64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .neg_u64 => .{ .name = "neg.u64", .format = .e, .code = 3, .rep = .u64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .neg_f32 => .{ .name = "neg.f32", .format = .e, .code = 4, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .neg_f64 => .{ .name = "neg.f64", .format = .e, .code = 5, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .abs_i32 => .{ .name = "abs.i32", .format = .e, .code = 8, .rep = .i32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .abs_i64 => .{ .name = "abs.i64", .format = .e, .code = 9, .rep = .i64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .abs_f32 => .{ .name = "abs.f32", .format = .e, .code = 10, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .abs_f64 => .{ .name = "abs.f64", .format = .e, .code = 11, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .clz_i32 => .{ .name = "clz.i32", .format = .e, .code = 12, .rep = .i32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .clz_i64 => .{ .name = "clz.i64", .format = .e, .code = 14, .rep = .i64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .popcount_i32 => .{ .name = "popcount.i32", .format = .e, .code = 16, .rep = .i32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .popcount_i64 => .{ .name = "popcount.i64", .format = .e, .code = 18, .rep = .i64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sqrt_f32 => .{ .name = "sqrt.f32", .format = .e, .code = 20, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .sqrt_f64 => .{ .name = "sqrt.f64", .format = .e, .code = 21, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .floor_f32 => .{ .name = "floor.f32", .format = .e, .code = 22, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .floor_f64 => .{ .name = "floor.f64", .format = .e, .code = 23, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .ceil_f32 => .{ .name = "ceil.f32", .format = .e, .code = 24, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .ceil_f64 => .{ .name = "ceil.f64", .format = .e, .code = 25, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .trunc_f32 => .{ .name = "trunc.f32", .format = .e, .code = 26, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .trunc_f64 => .{ .name = "trunc.f64", .format = .e, .code = 27, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .round_f32 => .{ .name = "round.f32", .format = .e, .code = 28, .rep = .f32, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .round_f64 => .{ .name = "round.f64", .format = .e, .code = 29, .rep = .f64, .a = .dst, .b = .src, .c = .none, .may_trap = false, .terminator = false },
        .not => .{ .name = "not", .format = .e, .code = 30, .rep = null, .a = .cond, .b = .cond, .c = .none, .may_trap = false, .terminator = false },
        .read_tag => .{ .name = "read_tag", .format = .e, .code = 31, .rep = null, .a = .dst, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .copy => .{ .name = "copy", .format = .e, .code = 32, .rep = null, .a = .cond, .b = .cond, .c = .none, .may_trap = false, .terminator = false },
        .borrow => .{ .name = "borrow", .format = .e, .code = 33, .rep = null, .a = .dst_real, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .move => .{ .name = "move", .format = .e, .code = 34, .rep = null, .a = .dst_real, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .release => .{ .name = "release", .format = .e, .code = 35, .rep = null, .a = .src_real, .b = .none, .c = .none, .may_trap = false, .terminator = false },
        .copy_retain => .{ .name = "copy_retain", .format = .e, .code = 36, .rep = null, .a = .dst, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .replace_copy => .{ .name = "replace_copy", .format = .e, .code = 37, .rep = null, .a = .dst, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .replace_move => .{ .name = "replace_move", .format = .e, .code = 38, .rep = null, .a = .dst, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .release_ret => .{ .name = "release_ret", .format = .e, .code = 39, .rep = null, .a = .src, .b = .src_f, .c = .none, .may_trap = false, .terminator = true },
        .ret => .{ .name = "ret", .format = .e, .code = 40, .rep = null, .a = .src, .b = .none, .c = .none, .may_trap = false, .terminator = true },
        .tailcall_self => .{ .name = "tailcall_self", .format = .e, .code = 41, .rep = null, .a = .none, .b = .none, .c = .none, .may_trap = false, .terminator = true },
        .trap => .{ .name = "trap", .format = .e, .code = 42, .rep = null, .a = .none, .b = .none, .c = .none, .may_trap = false, .terminator = true },
        .take => .{ .name = "take", .format = .e, .code = 43, .rep = null, .a = .dst, .b = .src_real, .c = .none, .may_trap = false, .terminator = false },
        .const_ => .{ .name = "const", .format = .i, .code = 0, .rep = null, .a = .dst, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .fn_ref => .{ .name = "fn_ref", .format = .i, .code = 1, .rep = null, .a = .dst, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .module_ref => .{ .name = "module_ref", .format = .i, .code = 2, .rep = null, .a = .dst, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .syscall => .{ .name = "syscall", .format = .i, .code = 3, .rep = null, .a = .dst, .b = .id, .c = .none, .may_trap = true, .terminator = false },
        .construct => .{ .name = "construct", .format = .i, .code = 4, .rep = null, .a = .dst, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .store_member => .{ .name = "store_member", .format = .i, .code = 5, .rep = null, .a = .src_real, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .unpack_struct => .{ .name = "unpack_struct", .format = .i, .code = 6, .rep = null, .a = .src_real, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .unpack_tuple => .{ .name = "unpack_tuple", .format = .i, .code = 7, .rep = null, .a = .src_real, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .split_list => .{ .name = "split_list", .format = .i, .code = 8, .rep = null, .a = .src_real, .b = .id, .c = .none, .may_trap = true, .terminator = false },
        .switch_ => .{ .name = "switch", .format = .i, .code = 9, .rep = null, .a = .src_real, .b = .id, .c = .none, .may_trap = true, .terminator = true },
        .jalr => .{ .name = "jalr", .format = .i, .code = 11, .rep = null, .a = .src, .b = .offs16, .c = .none, .may_trap = true, .terminator = true },
        .spill_take => .{ .name = "spill_take", .format = .i, .code = 12, .rep = null, .a = .src_t, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .spill_put => .{ .name = "spill_put", .format = .i, .code = 13, .rep = null, .a = .src_t, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .slot_retain => .{ .name = "slot_retain", .format = .i, .code = 14, .rep = null, .a = .src_f, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .slot_move => .{ .name = "slot_move", .format = .i, .code = 15, .rep = null, .a = .src_f, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .slot_borrow => .{ .name = "slot_borrow", .format = .i, .code = 16, .rep = null, .a = .src_f, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .slot_copy => .{ .name = "slot_copy", .format = .i, .code = 17, .rep = null, .a = .src_f, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .jr => .{ .name = "jr", .format = .i, .code = 18, .rep = null, .a = .src_real, .b = .offs16, .c = .none, .may_trap = true, .terminator = true },
        .drop => .{ .name = "drop", .format = .i, .code = 19, .rep = null, .a = .src_f, .b = .id, .c = .none, .may_trap = false, .terminator = false },
        .movwn0 => .{ .name = "movwn0", .format = .i, .code = 20, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwn1 => .{ .name = "movwn1", .format = .i, .code = 21, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwn2 => .{ .name = "movwn2", .format = .i, .code = 22, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwn3 => .{ .name = "movwn3", .format = .i, .code = 23, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwz0 => .{ .name = "movwz0", .format = .i, .code = 24, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwz1 => .{ .name = "movwz1", .format = .i, .code = 25, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwz2 => .{ .name = "movwz2", .format = .i, .code = 26, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwz3 => .{ .name = "movwz3", .format = .i, .code = 27, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwk0 => .{ .name = "movwk0", .format = .i, .code = 28, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwk1 => .{ .name = "movwk1", .format = .i, .code = 29, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwk2 => .{ .name = "movwk2", .format = .i, .code = 30, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .movwk3 => .{ .name = "movwk3", .format = .i, .code = 31, .rep = null, .a = .dst_movw, .b = .imm16, .c = .none, .may_trap = false, .terminator = false },
        .jal => .{ .name = "jal", .format = .u, .code = 0, .rep = null, .a = .link, .b = .imm20, .c = .none, .may_trap = false, .terminator = true },
        .j => .{ .name = "j", .format = .u, .code = 0, .rep = null, .a = .none, .b = .imm20, .c = .none, .may_trap = false, .terminator = true },
        .auipc => .{ .name = "auipc", .format = .u, .code = 1, .rep = null, .a = .dst_u, .b = .imm20, .c = .none, .may_trap = false, .terminator = false },
        .lui => .{ .name = "lui", .format = .u, .code = 2, .rep = null, .a = .dst_u, .b = .imm20, .c = .none, .may_trap = false, .terminator = false },
    };
}
